# -*- coding: utf-8 -*-
"""project 108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UayjZwiTnobwh5fB8ywJ2wgwplsMxciD
"""

import plotly.figure_factory as ff
import pandas as pd

df = pd.read_csv("data.csv")
print(df["Avg Rating"].tolist())

fig = ff.create_distplot([df["Avg Rating"].tolist()], ["Average Rating"])
fig.show()